# Problem 12: Highly divisible triangular number
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number
# would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#   1,3,6,10,15,21,28,36,45,55
# Let us list the factors of the first seven triangular numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

problem012 <- function() {
  # 28 = 2^2 * 7^1 = 2*2*7. Given 3 factors, there are 2^3=8 different subsets we can make
  # out of those factors: {},{2},{2},{7},{2,2},{2,7},{2,7},{2,2,7}. But notice that
  # these subsets aren't distinct; there's repeats.
  # Instead, lets reframe the problem as counts of each factor:
  # 28 = {2:2, 7:1}. The number of possible combinations of factor counts and the associated products is:
  # prod{2:0, 7:0} = 1
  # prod{2:1, 7:0} = 2
  # prod{2:2, 7:0} = 4
  # prod{2:0, 7:1} = 7
  # prod{2:1, 7:1} = 14
  # prod{2:2, 7:1} = 28.
  # In this case, the number of combinations is
  # {Factor 2 can be used 3 ways (0,1,or 2 times)} X {Factor 7 can be used 2 ways (0 or 1 time)} = 6 unique factors

  # Generalizing, for any positive integer n with prime factorization n = p1^e1 * p2^e2 * ... * pi^ei,
  # the factors we can generate are determined by the number combinations of factor counts:
  # {Factor p1 can be used e1+1 ways (i.e. 0,...,e1 times)} X
  # {Factor p2 can be used e2+1 ways (i.e. 0,...,e2 times)} X
  # ... X
  # {factor pi can be used ei+1 ways (i.e. 0,...,ei times)}
  # For a total of (e1+1) * (e2+1) * ... * (ei+1) unique factors.

  # Therefore the number of divisors of an integer n with prime factorization n = p1^e1 * p2^e2 * ... * pi^ei is
  # prod((e1+1),(e2+1),...,(ei+1)), the product of each prime factor exponent plus one.

  n_divisors <- function(n) {

  }


  # Where should we start our search of the triangle numbers so that we aren't wasting time searching too low?
  # When we take a lot of random samples of integers at various powers of 10 and plot the maximum # of divisors
  # as a function of log10(n), we find that around the 10 million (1e7) mark there exist in our sample numbers with
  # ~250 divisors. So lets start at a triangle number around 1e7.

  # set.seed(123)
  # tibble(n = c(
  #     sample.int(100,100), # 100 random samples in [0,100]
  #     1e3 + sample.int(9e3, 100), # 100 random samples in [1e3,1e4]
  #     1e4 + sample.int(9e4, 100), # 100 random samples in [1e4, 1e5]
  #     1e5 + sample.int(9e5, 100), # 100 random samples in [1e5,1e6]
  #     1e6 + sample.int(9e6, 100), # 100 random samples in [1e6,1e7]
  #     1e7 + sample.int(9e7, 100) # 100 random samples in [1e7,1e8]
  #   )) %>%
  #   rowwise() %>%
  #   mutate(n_divisors = n_divisors(n)) %>%
  #   group_by(log10_n = floor(log10(n))) %>%
  #   summarise(max_n_divisors = max(n_divisors)) %>%
  #   ggplot() +
  #   geom_line(aes(x=log10_n, y=max_n_divisors), ) +
  #   ggtitle("Maximum # of divisors as a function of n",subtitle="100 random samples from each power of 10")

  # Whats the smallest triangular number N > 1e7? The formula for triangle numbers is N = sum(1:n) = n*(n+1)/2
  # => n*(n+1)/2 > 1e7 => n ~= 4471.6. So lets start at 5000
  primes_cache <- primes_up_to_n(1e5)
  n <- 5000
  N <- n*(n+1)/2
  while(TRUE){
    factorization <- prime_factorization(N, primes_cache)
    n_divisors <- prod(factorization$exponent + 1)
    if(n_divisors > 500){
      return(N)
    }
    n <- n + 1
    N <- n*(n+1)/2
  }
}



