import * as utils from "../utils";

export function main(): number {
    // The sequence of triangle numbers is generated by adding the natural numbers. 
    // So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
    // The first ten terms would be:
    // 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    // Let us list the factors of the first seven triangle numbers:

    // 1: 1
    // 3: 1,3
    // 6: 1,2,3,6
    // 10: 1,2,5,10
    // 15: 1,3,5,15
    // 21: 1,3,7,21
    // 28: 1,2,4,7,14,28
    // We can see that 28 is the first triangle number to have over five divisors.

    // What is the value of the first triangle number to have over five hundred divisors?

    // The prime factorization of natural number n is given by n = sum(p_i^e_i, i=1...m)
    // The number of divisors of n is given by d(n) = product(e_i + 1, i = 1...m)
    // And for every natural n, d(n) < 2*sqrt(n).
    // Given that we're wanting to know the smallest triangular number n such that 500 < d(n),
    // we can combine this to get 500 < d(n) < 2*sqrt(n), which we can rearrange to obtain
    // n > 62500. So we'll start our search with triangular numbers greater than 62500. So which
    // triangular number should we start with? We know the ith triangular number is of the form
    // n = 1 + 2 + ... + i = i(i+1)/2, so we can conclude
    // i(i+1)/2 > 62500 => i*(i+1) > 125000 => i > ~sqrt(125000) = 353.55
    // So we'll start looking at around the 350th triangular number

    const primes = utils.primesUpTo(1_000_000) // use a cache of precomputed primes for factorization. Speeds things way up.

    let answer = 0
    for (let i = 350; ; i++) {
        const n = i * (i + 1) / 2
        const prime_factorization = utils.primeFactorization(n, primes)

        // The # of divisors of n is equal to the product of 1 added to
        // each of the exponents of the prime factorization of n
        const n_divisors = prime_factorization
            .map(p => p.power)
            .reduce((acc, pow) => acc * (pow + 1), 1.0)

        if (n_divisors > 500) {
            answer = n
            break
        }
    }
    return answer
}
