# Problem 2: Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

problem002 <- function() {
  fibonacci_terms_up_to_n(n=3999999) %>%
    subset(. %% 2 == 0) %>%
    sum()
}

fibonacci_first_n_terms <- function(n, previous = c()){
  # Returns a list of the first N terms of the fibonacci sequence,
  # starting from F_1 = 1, F_2 = 2.
  # Optionally, we can pass in a vector previous containing the first m < n
  # terms, in which case the work of this function is to calculate the
  # remaining n-m terms and return all n terms in a single vector.

  if(n == 1) {
    return(c(1))
  }

  if(n == 2) {
    return(c(1,2))
  }

  # First, initialize an entire vector of length n, with the
  # first m terms occupied by the contents of previous.
  X <- c(previous, rep(NA, n - length(previous)))


  X[1] = 1
  X[2] = 2

  # if previous is of length m < n, start filling in new values starting at index m+1,
  # but at minimum start at index 3 (since we filled in 1 and 2 above).
  starting_at <- pmax(length(previous) + 1, 3)
  for(i in starting_at:n) {
    X[i] = X[i-1] + X[i-2]
  }

  X
}

fibonacci_terms_up_to_n <- function(n) {
  # Generates all terms of the Fibonacci sequence that are less than or equal to n
  # Because we don't know the largest value of the first N terms, we'll successively
  # produce sequences of increasingly large length until we find our cutoff point.
  # We'll start with the first 50 terms and go from there

  N <- 50
  terms <- fibonacci_first_n_terms(N)
  while(tail(terms,n=1) < n) {
    N <- 2*N
    terms <- fibonacci_first_n_terms(N, previous=terms)
  }
  terms %>% subset(. <= n)
}
